"use client";
import { Download, Search } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { ProtectedRoute } from "@/components/shared/ProtectedRoute";
import { AppShell } from "@/components/users/AppShell";
import { fetchTransactions, getApiErrorMessage } from "@/lib/api";
import { downloadCsv } from "@/lib/export";
import { formatDateTime, formatMoney, startCase } from "@/lib/format";
import { mockTransactions } from "@/lib/mock-data";
import { Transaction } from "@/types/transaction";

export default function TransactionsPage() {
  const [transactions, setTransactions] = useState<Transaction[]>(mockTransactions); const [search, setSearch] = useState(""); const [filter, setFilter] = useState("all"); const [error, setError] = useState<string | null>(null);
  useEffect(() => { fetchTransactions().then((r) => setTransactions(r.data)).catch((e) => setError(getApiErrorMessage(e))); }, []);
  const visible = useMemo(() => transactions.filter((item) => (filter === "all" || item.direction === filter || item.transaction_type === filter) && `${item.reference} ${item.description ?? ""}`.toLowerCase().includes(search.toLowerCase())), [filter, search, transactions]);
  return <ProtectedRoute><AppShell title="Transaction history" description="Review every credit, debit, payment, and receipt.">{error ? <p className="mb-4 text-[10px] text-rose-300">{error}</p> : null}<div className="rounded-2xl border border-white/[0.07] bg-white/[0.02] p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-center"><div className="flex flex-wrap gap-2">{["all","credit","debit","funding","airtime","bill_payment"].map((item) => <button key={item} onClick={() => setFilter(item)} className={`rounded-lg px-3 py-2 text-[9px] ${filter === item ? "bg-emerald-400 text-[#07100b]" : "border border-white/[0.07] text-white/40"}`}>{startCase(item)}</button>)}</div><div className="ml-auto flex gap-2"><label className="flex items-center gap-2 rounded-lg border border-white/[0.08] px-3"><Search className="h-3 w-3 text-white/25" /><input className="h-9 bg-transparent text-[10px] outline-none placeholder:text-white/20" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search activity" /></label><button onClick={() => downloadCsv("my-stpay-transactions.csv", visible)} className="rounded-lg border border-white/[0.08] px-3 text-white/45"><Download className="h-3.5 w-3.5" /></button></div></div><div className="mt-4 overflow-x-auto"><table className="min-w-full text-left text-[10px]"><thead className="text-white/25"><tr><th className="px-3 py-3">Reference</th><th className="px-3 py-3">Activity</th><th className="px-3 py-3">Amount</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Date</th></tr></thead><tbody>{visible.map((item) => <tr key={item.id} className="border-t border-white/[0.06] text-white/50"><td className="px-3 py-4 font-medium text-white/75">{item.reference}</td><td className="px-3 py-4">{startCase(item.direction)} · {startCase(item.transaction_type)}<p className="mt-1 text-[8px] text-white/25">{item.description}</p></td><td className={`px-3 py-4 font-semibold ${item.direction === "credit" ? "text-emerald-300" : "text-white/70"}`}>{item.direction === "credit" ? "+" : "-"}{formatMoney(item.amount)}</td><td className="px-3 py-4">{startCase(item.status)}</td><td className="px-3 py-4">{formatDateTime(item.created_at)}</td></tr>)}{!visible.length ? <tr><td colSpan={5} className="py-12 text-center text-white/25">No transactions found.</td></tr> : null}</tbody></table></div></div></AppShell></ProtectedRoute>;
}
