BILL_PROVIDERS = {
    "Electricity": {
        "Abuja Electricity Distribution Company",
        "Aba Power",
        "Benin Electricity Distribution Company",
        "Eko Electricity Distribution Company",
        "Enugu Electricity Distribution Company",
        "Ibadan Electricity Distribution Company",
        "Ikeja Electric",
        "Jos Electricity Distribution",
        "Kaduna Electric",
        "Kano Electricity Distribution Company",
        "Port Harcourt Electricity Distribution",
        "Yola Electricity Distribution Company",
    },
    "Cable TV": {"DStv", "GOtv", "StarTimes", "Showmax"},
    "Internet": {
        "Spectranet",
        "Smile Communications",
        "ipNX Nigeria",
        "FibreOne Broadband",
        "Tizeti",
        "MTN Broadband",
        "Airtel Broadband",
        "Glo Broadband",
    },
    "School Fees": {
        "Joint Admissions and Matriculation Board",
        "West African Examinations Council",
        "National Examinations Council",
        "University of Lagos",
        "University of Ibadan",
        "Covenant University",
    },
    "Water Bill": {
        "Lagos Water Corporation",
        "FCT Water Board",
        "Ogun State Water Corporation",
        "Kaduna State Water Corporation",
        "Oyo State Water Corporation",
        "Rivers State Water Services",
    },
}
