"use client";
import { FormEvent, useState } from "react";
import { BankingForm, bankingFieldClass, bankingLabelClass, OperationResult, SubmitButton } from "@/components/users/BankingForm";
import { ProtectedRoute } from "@/components/shared/ProtectedRoute";
import { AppShell } from "@/components/users/AppShell";
import { getApiErrorMessage, transferMoney } from "@/lib/api";

export default function SendMoneyPage() {
  const [form, setForm] = useState({ receiver_account_number: "", amount: "", description: "", transaction_pin: "" }); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [result, setResult] = useState<{ reference: string; balance: number } | null>(null);
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(null); try { const response = await transferMoney({ ...form, amount: Number(form.amount) }); setResult(response.data); setForm({ receiver_account_number: "", amount: "", description: "", transaction_pin: "" }); } catch (err) { setError(getApiErrorMessage(err)); } finally { setLoading(false); } }
  const set = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  return <ProtectedRoute><AppShell title="Send money" description="Transfer securely to another STPay wallet."><BankingForm title="New transfer" note="Confirm the recipient account number carefully before completing the transfer." side={result ? <OperationResult {...result} message="Transfer completed successfully" /> : undefined}><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><label className={`${bankingLabelClass} sm:col-span-2`}>Receiver account number<input className={bankingFieldClass} value={form.receiver_account_number} onChange={(e) => set("receiver_account_number", e.target.value)} maxLength={10} placeholder="10-digit STPay account" required /></label><label className={bankingLabelClass}>Amount<input className={bankingFieldClass} type="number" min="1" value={form.amount} onChange={(e) => set("amount", e.target.value)} required /></label><label className={bankingLabelClass}>Transaction PIN<input className={bankingFieldClass} type="password" inputMode="numeric" maxLength={4} value={form.transaction_pin} onChange={(e) => set("transaction_pin", e.target.value)} required /></label><label className={`${bankingLabelClass} sm:col-span-2`}>Description<input className={bankingFieldClass} value={form.description} onChange={(e) => set("description", e.target.value)} placeholder="What is this payment for?" /></label>{error ? <p className="text-[10px] text-rose-300 sm:col-span-2">{error}</p> : null}<SubmitButton loading={loading} label="Send money" /></form></BankingForm></AppShell></ProtectedRoute>;
}
