"use client";
import { FormEvent, useState } from "react";
import { BankingForm, bankingFieldClass, bankingLabelClass, OperationResult, SubmitButton } from "@/components/users/BankingForm";
import { ProtectedRoute } from "@/components/shared/ProtectedRoute";
import { AppShell } from "@/components/users/AppShell";
import { buyAirtime, getApiErrorMessage } from "@/lib/api";

export default function AirtimePage() {
  const [form, setForm] = useState({ network_provider: "MTN", phone_number: "", amount: "", transaction_pin: "" }); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [result, setResult] = useState<{ reference: string; balance: number } | null>(null);
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(null); try { const response = await buyAirtime({ ...form, amount: Number(form.amount) }); setResult(response.data); } catch (err) { setError(getApiErrorMessage(err)); } finally { setLoading(false); } } const set = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  return <ProtectedRoute><AppShell title="Buy airtime" description="Top up any supported mobile number from your wallet."><BankingForm title="Airtime purchase" note="A receipt and account alert will be created after a successful purchase." side={result ? <OperationResult {...result} message="Airtime purchase successful" /> : undefined}><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><label className={bankingLabelClass}>Network<select className={bankingFieldClass} value={form.network_provider} onChange={(e) => set("network_provider", e.target.value)}>{["MTN","Airtel","Glo","9mobile"].map((item) => <option className="bg-[#111512]" key={item}>{item}</option>)}</select></label><label className={bankingLabelClass}>Phone number<input className={bankingFieldClass} value={form.phone_number} onChange={(e) => set("phone_number", e.target.value)} placeholder="080..." required /></label><label className={bankingLabelClass}>Amount<input className={bankingFieldClass} type="number" min="1" value={form.amount} onChange={(e) => set("amount", e.target.value)} required /></label><label className={bankingLabelClass}>Transaction PIN<input className={bankingFieldClass} type="password" maxLength={4} inputMode="numeric" value={form.transaction_pin} onChange={(e) => set("transaction_pin", e.target.value)} required /></label>{error ? <p className="text-[10px] text-rose-300 sm:col-span-2">{error}</p> : null}<SubmitButton loading={loading} label="Buy airtime" /></form></BankingForm></AppShell></ProtectedRoute>;
}
