"use client";
import { FormEvent, useState } from "react";
import { BankingForm, bankingFieldClass, bankingLabelClass, OperationResult, SubmitButton } from "@/components/users/BankingForm";
import { ProtectedRoute } from "@/components/shared/ProtectedRoute";
import { AppShell } from "@/components/users/AppShell";
import { getApiErrorMessage, payBill } from "@/lib/api";

export default function BillsPage() {
  const [form, setForm] = useState({ category: "Electricity", provider: "", customer_number: "", amount: "", transaction_pin: "" }); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [result, setResult] = useState<{ reference: string; balance: number } | null>(null); const set = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(null); try { const response = await payBill({ ...form, amount: Number(form.amount) }); setResult(response.data); } catch (err) { setError(getApiErrorMessage(err)); } finally { setLoading(false); } }
  return <ProtectedRoute><AppShell title="Pay bills" description="Settle everyday services securely from your STPay wallet."><BankingForm title="Bill payment" note="Enter the provider and customer reference exactly as shown on your service account." side={result ? <OperationResult {...result} message="Bill payment successful" /> : undefined}><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><label className={bankingLabelClass}>Category<select className={bankingFieldClass} value={form.category} onChange={(e) => set("category", e.target.value)}>{["Electricity","Cable TV","Internet","School Fees","Water Bill"].map((item) => <option className="bg-[#111512]" key={item}>{item}</option>)}</select></label><label className={bankingLabelClass}>Provider<input className={bankingFieldClass} value={form.provider} onChange={(e) => set("provider", e.target.value)} placeholder="Provider name" required /></label><label className={bankingLabelClass}>Customer/account number<input className={bankingFieldClass} value={form.customer_number} onChange={(e) => set("customer_number", e.target.value)} required /></label><label className={bankingLabelClass}>Amount<input className={bankingFieldClass} type="number" min="1" value={form.amount} onChange={(e) => set("amount", e.target.value)} required /></label><label className={bankingLabelClass}>Transaction PIN<input className={bankingFieldClass} type="password" maxLength={4} inputMode="numeric" value={form.transaction_pin} onChange={(e) => set("transaction_pin", e.target.value)} required /></label>{error ? <p className="text-[10px] text-rose-300 sm:col-span-2">{error}</p> : null}<SubmitButton loading={loading} label="Pay bill" /></form></BankingForm></AppShell></ProtectedRoute>;
}
